---
title: "Jamo Analysis"
author: "Ryan Jiang"
format: pdf
editor: visual
---

```{r}
library(maps)
library(tidyverse)
library(ggplot2)
library(stringr)
library(dplyr)
library(purrr)
library(scales)
```

```{r}
unique <- readRDS("~/YKim-Linguistics/ykim_korean-analysis/Data/unique_database.rds")

# no column 3, 5, 6 from unique database
# clean_unique_database <- readRDS("~/YKim-Linguistics/ykim_korean-analysis/Data/clean_unique_database.rds")

```

```{r}
# Creates a summation of the appearance of all the rules across the dataset - Not moving in this direction anymore, check google doc
#rules_summary <- only_U_1100 |>
#  mutate(rule_sums = map(Jamo_Rule_Matrix, ~ colSums(.x[,-1], na.rm = TRUE))) |>
#  pull(rule_sums) |>
#  bind_rows() |>
#  summarize(across(everything(), sum))

```

```{r}
# NOT DOING THIS ANYMORE

#U_1100_rules_counts <- rules_summary |>
#  pivot_longer(everything(), names_to = "rule", values_to = "count")

#ggplot(U_1100_rules_counts, aes(x = reorder(rule, count), y = count)) +
#  geom_col() +
#  coord_flip() + 
#  labs(
#    x = "Rule",
#    y = "Counts",
#    title = "Rules in order of frequency of words/phrases containing U+1100"
#  ) +
#  theme_minimal()

```

Working with frequency values rather than the unique word set to account for relevance and usage of certain words for more realistic distributions.

```{r}
# dataset with only values with frequency and proportions
clean_unique <- unique |>
  filter(!is.na(total_instances), !is.na(freq))

# dataset with only values without frequency and proportions
#na_unique <- unique |>
#  filter(is.na(total_instances), is.na(freq))
```

Jamo Unicode Analysis

```{r}
# JAMO UNICODE ANALYSIS
########################################################################################################################################

# UNWEIGHTED
#------------------------------------------------------------------------------------------------------------
# PROPORTION PLOT

unicode_count <- unique |>
  mutate(word_id = row_number()) |>
  mutate(uc = str_extract_all(Jamo_Cleaned_Unicode, "U\\+[0-9A-F]{4}")) |>
  unnest(uc) |>
  # keep only one instance of a unicode per word
  distinct(word_id, uc, .keep_all = TRUE) 

total_unique_words <- nrow(unique)

unicode_df_unweighted <- unicode_count |>
  group_by(uc) |>
  summarize(
    words_affected = n(), 
    prop_removed = words_affected / total_unique_words,
    .groups = "drop"
  )

jamo_unweighted_proportions <- ggplot(unicode_df_unweighted, aes(x = reorder(uc, prop_removed), y = prop_removed)) +
  geom_col() +
  coord_flip() +
  theme_minimal() +
  scale_y_continuous(labels = scales::percent) +
  labs(
    y = "Proportion of Hangul Lost",
    x = "Jamo Unicode",
    title = "Effect of Jamo Unicode Removal on Hangul (Unweighted by Word Frequencies)",
  )

ggsave("jamo_unweighted_proportions.pdf", plot = jamo_unweighted_proportions, width = 8, height = 6)

#############################################################################################################################

# FREQUENCY PLOT

unicode_counts_total <- unique |>
  mutate(uc = str_extract_all(Jamo_Cleaned_Unicode, "U\\+[0-9A-F]{4}")) |>
  unnest(uc)

unicode_df_total <- unicode_counts_total |>
  group_by(uc) |>
  summarize(
    total_freq = n(),
    prop_of_all_jamo = total_freq / total_unique_words,
    .groups = "drop"
  )
  
jamo_unweighted_frequency <- ggplot(unicode_df_total, aes(x = reorder(uc, total_freq), y = total_freq)) +
  geom_col() +
  geom_text(
    aes(label = comma(total_freq)),
    hjust = -0.1,
    size = 3,
    fontface = "italic"
  ) +
  coord_flip() +
  theme_minimal() +
  scale_y_continuous(labels = label_comma(),
                     expand = expansion(mult = c(0, 0.1))) +
  labs(
    y = "Jamo Unicode Frequencies",
    x = "Jamo Unicode",
    title = "Total Instances of Jamo Unicodes (Unweighted by Word Frequencies)",
  )

ggsave("jamo_unweighted_frequency.pdf", plot = jamo_unweighted_frequency, width = 8, height = 6)


# WEIGHTED
#------------------------------------------------------------------------------------------------------------
# PROPORTION PLOT

# find frequency of each unicode (modified to count each unicode only once per word)
unicode_freq_2 <- clean_unique |>
  mutate(uni = str_extract_all(Jamo_Cleaned_Unicode, "U\\+[0-9A-F]{4}")) |>
  mutate(uni = purrr::map(uni, \(x) base::unique(x))) |> 
  unnest(uni) |>
  group_by(uni) |>
  summarize(total_freq = sum(total_instances), .groups = "drop")

total_counts <- sum(clean_unique$total_instances, na.rm = TRUE)

unicode_freq_2 <- unicode_freq_2 |>
  mutate(
    prop = total_freq / total_counts
  )

# lowkey more interpretable as a table

clean_uni_freq_2 <- unicode_freq_2 |>
  ggplot(aes(x = reorder(uni, prop), y = prop)) +
  geom_col() +
  coord_flip() +
  scale_y_continuous(labels = scales::percent) +
  theme_minimal() +
  labs(
    x = "Jamo Unicode",
    y = "Proportion of Hangul Lost",
    title = "Effect of Jamo Unicode Removal on Hangul (Weighted by Word Frequencies)"
  )

ggsave("jamo_weighted_proportion.pdf", plot = clean_uni_freq_2, width = 8, height = 6)

#############################################################################################################################

# FREQUENCY PLOT

# find frequency of each unicode
unicode_freq <- clean_unique |>
  mutate(uni = str_extract_all(Jamo_Cleaned_Unicode, "U\\+[0-9A-F]{4}")) |>
  unnest(uni) |>
  group_by(uni) |>
  summarize(total_freq = sum(total_instances), .groups = "drop")

# calculate the proportion
unicode_freq <- unicode_freq |>
  mutate(
    prop = total_freq / sum(total_freq)
    )

clean_uni_freq <- unicode_freq |>
  ggplot(aes(x = reorder(uni, total_freq), y = total_freq)) +
  geom_col() +
  geom_text(
    aes(label = comma(total_freq)),
    hjust = -0.1,
    size = 2.5,
    fontface = "italic"
  ) +
  coord_flip() +
  scale_y_continuous(label = label_comma(),
                     expand = expansion(mult = c(0, 0.1))) +
  theme_minimal() +
  labs(
    x = "Jamo Unicode",
    y = "Jamo Unicode Frequencies",
    title = "Total Instances of Jamo Unicodes (Weighted by Word Frequencies)"
  )

ggsave("jamo_weighted_frequency.pdf", plot = clean_uni_freq, width = 8, height = 6)
```

IPA Unicode Analysis

```{r}
# IPA UNICODE ANALYSIS
########################################################################################################################################

# UNWEIGHTED
#------------------------------------------------------------------------------------------------------------
# PROPORTION PLOT

unicode_count <- unique |>
  mutate(
    word_id = row_number(),
    IPA_Syllable_Unicode = str_replace_all(
      IPA_Syllable_Unicode,
      "\\s*,\\s*",
      ""
    )
  ) |>
  mutate(uc = str_split(IPA_Syllable_Unicode, " ")) |>
  unnest(uc) |>
  distinct(word_id, uc, .keep_all = TRUE)

total_unique_words <- nrow(unique)

unicode_df_unweighted <- unicode_count |>
  group_by(uc) |>
  summarize(
    words_affected = n(), 
    prop_removed = words_affected / total_unique_words,
    .groups = "drop"
  )

ipa_unweighted_proportions <- ggplot(unicode_df_unweighted, aes(x = reorder(uc, prop_removed), y = prop_removed)) +
  geom_col() +
  coord_flip() +
  theme_minimal() +
  scale_y_continuous(labels = scales::percent) +
  labs(
    y = "Proportion of Hangul Lost",
    x = "IPA Syllable Unicode",
    title = "Effect of IPA Syllable Removal on Hangul (Unweighted by Word Frequencies)",
  )

ggsave("ipa_unweighted_proportions.pdf", plot = ipa_unweighted_proportions, width = 8, height = 6)

#############################################################################################################################

# FREQUENCY PLOT

unicode_counts_total <- unique |>
  mutate(
    IPA_Syllable_Unicode = str_replace_all(
      IPA_Syllable_Unicode,
      "\\s*,\\s*",
      ""
    )
  ) |>
  mutate(uc = str_split(IPA_Syllable_Unicode, " ")) |>
  unnest(uc)

unicode_df_total <- unicode_counts_total |>
  group_by(uc) |>
  summarize(
    total_freq = n(),
    prop_of_all_jamo = total_freq / total_unique_words,
    .groups = "drop"
  )
  
ipa_unweighted_frequency <- ggplot(unicode_df_total, aes(x = reorder(uc, total_freq), y = total_freq)) +
  geom_col() +
  geom_text(
    aes(label = comma(total_freq)),
    hjust = -0.1,
    size = 3,
    fontface = "italic"
  ) +
  coord_flip() +
  theme_minimal() +
  scale_y_continuous(labels = label_comma(),
                     expand = expansion(mult = c(0, 0.1))) +
  labs(
    y = "IPA Syllable Frequencies",
    x = "IPA Syllable Unicode",
    title = "Total Instances of IPA Syllables (Unweighted by Word Frequencies)",
  )

ggsave("ipa_unweighted_frequency.pdf", plot = ipa_unweighted_frequency, width = 8, height = 6)


# WEIGHTED
#------------------------------------------------------------------------------------------------------------
# PROPORTION PLOT

# find frequency of each unicode (modified to count each unicode only once per word)
unicode_freq_2 <- clean_unique |>
  mutate(
    IPA_Syllable_Unicode = str_replace_all(
      IPA_Syllable_Unicode,
      "\\s*,\\s*",
      ""
    ),
    uni = str_split(IPA_Syllable_Unicode, " "),
    uni = purrr::map(uni, base::unique)
  ) |>
  unnest(uni) |>
  group_by(uni) |>
  summarize(total_freq = sum(total_instances), .groups = "drop")

total_counts <- sum(clean_unique$total_instances, na.rm = TRUE)

unicode_freq_2 <- unicode_freq_2 |>
  mutate(
    prop = total_freq / total_counts
  )

# lowkey more interpretable as a table

ipa_clean_uni_freq_2 <- unicode_freq_2 |>
  ggplot(aes(x = reorder(uni, prop), y = prop)) +
  geom_col() +
  coord_flip() +
  scale_y_continuous(labels = scales::percent) +
  theme_minimal() +
  labs(
    x = "IPA Syllable Unicode",
    y = "Proportion of Hangul Lost",
    title = "Effect of IPA Syllable Removal on Hangul (Weighted by Word Frequencies)"
  )

ggsave("ipa_weighted_proportion.pdf", plot = ipa_clean_uni_freq_2, width = 8, height = 6)

#############################################################################################################################

# FREQUENCY PLOT

# find frequency of each unicode
unicode_freq <- clean_unique |>
  mutate(
    IPA_Syllable_Unicode = str_replace_all(
      IPA_Syllable_Unicode,
      "\\s*,\\s*",
      ""
    ),
    uni = str_split(IPA_Syllable_Unicode, " ")
  ) |>
  unnest(uni) |>
  group_by(uni) |>
  summarize(total_freq = sum(total_instances), .groups = "drop")


# calculate the proportion
unicode_freq <- unicode_freq |>
  mutate(
    prop = total_freq / sum(total_freq)
    )

ipa_clean_uni_freq <- unicode_freq |>
  ggplot(aes(x = reorder(uni, total_freq), y = total_freq)) +
  geom_col() +
  geom_text(
    aes(label = comma(total_freq)),
    hjust = -0.1,
    size = 2.5,
    fontface = "italic"
  ) +
  coord_flip() +
  scale_y_continuous(label = label_comma(),
                     expand = expansion(mult = c(0, 0.1))) +
  theme_minimal() +
  labs(
    x = "IPA Syllable Unicode",
    y = "IPA Syllable Frequencies",
    title = "Total Instances of IPA Syllables (Weighted by Word Frequencies)"
  )

ggsave("ipa_weighted_frequency.pdf", plot = ipa_clean_uni_freq, width = 8, height = 6)
```

Glyph Best Rules Analysis

```{r}
# RULE UNICODE ANALYSIS
########################################################################################################################################

# UNWEIGHTED
#------------------------------------------------------------------------------------------------------------
# PROPORTION PLOT

# creating list of names based on column names of the matrices
rules <- colnames(unique$Jamo_Rule_Matrix[[1]])[-1]

rule_results <- vector("list", length(rules))

# iterating through each rule and detecting if the matrices contain the rule
for (i in seq_along(rules)) {
  r <- rules[i]
  
  # proportion of unique words affected
  contains_rule <- map_lgl(unique$Jamo_Rule_Matrix, function(x) {
    col_vec <- as.numeric(x[[r]])
    any(col_vec == 1, na.rm = TRUE)
  })
  
  # total count of every instance
  total_rule_instances <- map_dbl(unique$Jamo_Rule_Matrix, function(x) {
    col_vec <- as.numeric(x[[r]])
    sum(col_vec, na.rm = TRUE)
  })
  
  rule_results[[i]] <- tibble(
    rule = r,
    unique_words_affected = sum(contains_rule),
    prop_removed = mean(contains_rule),
    total_frequency = sum(total_rule_instances)
  )
}

rule_df <- bind_rows(rule_results)

# plotting df
rule_proportions <- rule_df |>
  ggplot(aes(x = reorder(rule, prop_removed), y = prop_removed)) +
  geom_col() +
  coord_flip() +
  theme_minimal() +
  labs(
    x = "Glyph Rules",
    y = "Proportion of Hangul Lost",
    title = "Effect of Rule Removal on Hangul (Unweighted by Word Frequency)"
  )

ggsave("rule_unweighted_proportions.pdf", plot = rule_proportions, width = 8, height = 6)

#############################################################################################################################

# FREQUENCY PLOT

rule_unweighted_frequency <- rule_df |>
  ggplot(aes(x = reorder(rule, total_frequency), y = total_frequency)) +
  geom_col() +
  geom_text(
    aes(label = comma(total_frequency)),
    hjust = -0.1,
    size = 2.5,
    fontface = "italic"
  ) +
  coord_flip() +
  scale_y_continuous(labels = label_comma(),
                     expand = expansion(mult = c(0, 0.1))) +
  theme_minimal() +
  labs(
    x = "Glyph Rules",
    y = "Rule Frequencies",
    title = "Total Instances of Glyph Rules (Unweighted by Word Frequencies)",
  )

# Save the plot
ggsave("rule_unweighted_frequency.pdf", plot = rule_unweighted_frequency, width = 8, height = 6)

# WEIGHTED
#------------------------------------------------------------------------------------------------------------
# PROPORTION PLOT

clean_rule_results <- vector("list", length(rules))

total_corpus_instances <- sum(clean_unique$total_instances, na.rm = TRUE)

# iterating through each rule and calculating weighted impact
for (i in seq_along(rules)) {
  r <- rules[i]
  
  contains_rule <- map_lgl(clean_unique$Jamo_Rule_Matrix, function(x) {
    col_vec <- as.numeric(x[[r]])
    any(col_vec == 1, na.rm = TRUE)
  })
  
  instances_per_word <- map_dbl(clean_unique$Jamo_Rule_Matrix, function(x) {
    col_vec <- as.numeric(x[[r]])
    sum(col_vec, na.rm = TRUE)
  })
  
  clean_rule_results[[i]] <- tibble(
    rule = r,
    total_weighted_freq = sum(instances_per_word * clean_unique$total_instances, na.rm = TRUE),
    weighted_words_affected = sum(clean_unique$total_instances[contains_rule], na.rm = TRUE),
    prop_removed = sum(clean_unique$total_instances[contains_rule], na.rm = TRUE) / total_corpus_instances
  )
}

clean_rule_df <- bind_rows(clean_rule_results)

# plotting Weighted Proportion
rule_weighted_proportions <- clean_rule_df |>
  ggplot(aes(x = reorder(rule, prop_removed), y = prop_removed)) +
  geom_col() +
  coord_flip() +
  scale_y_continuous(labels = scales::percent) +
  theme_minimal() +
  labs(
    x = "Glyph Rules",
    y = "Proportion of Hangul Lost",
    title = "Effect of Rule Removal on Hangul (Weighted by Word Frequency)"
  )

ggsave("rule_weighted_proportions.pdf", plot = rule_weighted_proportions, width = 8, height = 6)

#############################################################################################################################

# FREQUENCY PLOT

# find frequency of each unicode
rule_weighted_frequency <- clean_rule_df |>
  ggplot(aes(x = reorder(rule, total_weighted_freq), y = total_weighted_freq)) +
  geom_col() +
  geom_text(
    aes(label = comma(total_weighted_freq)),
    hjust = -0.1,
    size = 2.5,
    fontface = "italic"
  ) +
  coord_flip() +
  scale_y_continuous(labels = label_comma(),
                     expand = expansion(mult = c(0, 0.15))) +
  theme_minimal() +
  labs(
    x = "Glyph Rules",
    y = "Rule Frequencies",
    title = "Total Instances of Glyph Rules (Weighted by Word Frequencies)",
  )

# Save the plot
ggsave("rule_weighted_frequency.pdf", plot = rule_weighted_frequency, width = 8, height = 6)
```

```{r}
# GRAMMATICAL PARTS

# pulling all instances of unique grammatical parts to iterate over later
grammatical_parts <- clean_unique |>
  separate_rows(품사, sep = "\\s*,\\s*") |>
  pull(품사) |>
  unique()

# split grammatical parts into multiple rows/observations with a single grammatical part
clean_unique_parts <- clean_unique |>
  separate_rows(품사, sep = "\\s*,\\s*")

# calculating frequency by grammatical part to account for a word's relevance in Hangul
parts_totals <- clean_unique_parts |>
  group_by(품사) |>
  summarize(total_freq = sum(freq), .groups = "drop")

# function to calculate the proportion of each grammatical part is removed when a specific rule is removed
rule_parts_prop <- map_dfr(rules, function(r) {

  affected <- map_lgl(
    clean_unique_parts$Jamo_Rule_Matrix,
    ~ any(.x[, r] == 1)
  )

  clean_unique_parts[affected, ] |>
    distinct(어휘_cleaned, 품사, freq) |>
    group_by(품사) |>
    summarize(removed_freq = sum(freq), .groups = "drop") |>
    left_join(parts_totals, by = "품사") |>
    mutate(
        rule = r,
        prop_removed = removed_freq / total_freq
    ) |>
    select(품사, rule, prop_removed)
})

# iterate through each grammatical part and plot its respective proportions removed by each rule
walk(grammatical_parts, function(part) {

  p <- ggplot(
    rule_parts_prop |> filter(품사 == part),
    aes(x = reorder(rule, prop_removed), y = prop_removed)
  ) +
    geom_col() +
    coord_flip() +
    theme_minimal() +
    labs(
      x = "Rule Removed",
      y = "Proportion of Grammatical Part Removed",
      title = paste("Effect of Rule Removal —", part)
    )

  print(p)
})
```

```{r}
# Grammatical Parts by Jamo Unicode

# splitting up cells with multiple grammatical parts and Jamo unicode into individual rows

clean_unique_long <- clean_unique |>
  separate_rows(품사, sep = "\\s*,\\s*") |>
  separate_rows(Jamo_Cleaned_Unicode, sep = "\\s+")

# calculating proportion of a grammatical part is removed when a specific rule is removed
jamo_parts_prop <- clean_unique_long |>
  distinct(어휘_cleaned, 품사, Jamo_Cleaned_Unicode, freq) |>
  group_by(품사, Jamo_Cleaned_Unicode) |>
  summarize(
    removed_freq = sum(freq),
    .groups = "drop"
  ) |>
  left_join(parts_totals, by = "품사") |>
  mutate(
    prop_removed = removed_freq / total_freq
  ) |>
  rename(jamo_unicode = Jamo_Cleaned_Unicode)



# iterating through each unique grammatical part and plotting each distribution plot

walk(grammatical_parts, function(parts) {
  df <- jamo_parts_prop |> filter(품사 == parts)
  if (nrow(df) == 0) return(NULL)
  p <- ggplot(
    df,
    aes(x = reorder(jamo_unicode, prop_removed),
        y = prop_removed)
  ) +
    geom_col() +
    coord_flip() +
    theme_minimal() +
    labs(
      x = "Jamo Unicode Removed",
      y = "Proportion of Grammatical Part Removed",
      title = paste("Effect of Jamo Unicode Removal —", parts)
    )
  print(p)
})


```

```{r}
# WORD ORIGINS

# pulling unique word origins
word_origins <- clean_unique |>
  separate_rows(고유어_여부, sep = "\\s*,\\s*") |>
  pull(고유어_여부) |>
  unique()

# split word origins into multiple rows
clean_unique_origins <- clean_unique |>
  separate_rows(고유어_여부, sep = "\\s*,\\s*")

# calculating total frequencies for each word origin category
origin_totals <- clean_unique_origins |>
  group_by(고유어_여부) |>
  summarize(total_freq = sum(freq), .groups = "drop")

# calculating proportion of each word origin category removed when a specific rule is removed
rule_origin_prop <- map_dfr(rules, function(r) {

  affected <- map_lgl(
    clean_unique_origins$Jamo_Rule_Matrix,
    ~ any(.x[, r] == 1)
  )

  clean_unique_origins[affected, ] |>
    distinct(어휘_cleaned, 고유어_여부, freq) |>
    group_by(고유어_여부) |>
    summarize(removed_freq = sum(freq), .groups = "drop") |>
    left_join(origin_totals, by = "고유어_여부") |>
    mutate(
      rule = r,
      prop_removed = removed_freq / total_freq
    ) |>
    select(고유어_여부, rule, prop_removed)
})

# iterating through each word origin category and creating a plot displaying the proportion of a word origin category removed when a rule is removed
walk(word_origins, function(origin) {

  p <- ggplot(
    rule_origin_prop |> filter(고유어_여부 == origin),
    aes(x = reorder(rule, prop_removed), y = prop_removed)
  ) +
    geom_col() +
    coord_flip() +
    theme_minimal() +
    labs(
      x = "Rule Removed",
      y = "Proportion of Word Origin Removed",
      title = paste("Effect of Rule Removal —", origin)
    )

  print(p)
})

```

```{r}
# Word Origins by Jamo Unicode

# creating a dataframe with each origin category and unicode split into separate rows
clean_unique_origins_unicode <- clean_unique |>
  separate_rows(고유어_여부, sep = "\\s*,\\s*") |>
  separate_rows(Jamo_Cleaned_Unicode, sep = "\\s+")

# calculating proportion of each word origin category removed when a Jamo unicode is removed
jamo_origins_prop <- clean_unique_origins_unicode |>
  distinct(어휘_cleaned, 고유어_여부, Jamo_Cleaned_Unicode, freq) |>
  group_by(고유어_여부, Jamo_Cleaned_Unicode) |>
  summarize(
    removed_freq = sum(freq),
    .groups = "drop"
  ) |>
  left_join(origin_totals, by = "고유어_여부") |>
  mutate(
    prop_removed = removed_freq / total_freq
  ) |>
  rename(jamo_unicode = Jamo_Cleaned_Unicode)

# iterating through each word origin category and creating a plot displaying the proportion of a word origin category removed when a unicode is removed
walk(word_origins, function(origin) {

  df <- jamo_origins_prop |> filter(고유어_여부 == origin)
  if (nrow(df) == 0) return(NULL)

  p <- ggplot(
    df,
    aes(x = reorder(jamo_unicode, prop_removed),
        y = prop_removed)
  ) +
    geom_col() +
    coord_flip() +
    theme_minimal() +
    labs(
      x = "Jamo Unicode Removed",
      y = "Proportion of Word Origins Removed",
      title = paste("Effect of Jamo Unicode Removal —", origin)
    )

  print(p)
})
```
